### PR TITLE
Feature: Null Safety

### PR DESCRIPTION
**Pull request by lempiy**
My package depends on flutter-arrow-path, so it would be great if you merge this changes.

* Add null safety
* Change SDK version dependency to `>=2.12.0 <3.0.0`.
* Change lib version to `1.1.0`.

screen

### CODE REVIEW

**Comment by quentinleguennec** [comment]
Thanks @lempiy !
I'll try and test it this week, and I'll get back to you.

**Review by quentinleguennec — CHANGES_REQUESTED** [review]
@lempiy That's almost ready for merging, there are 2 changes I'll request first though:

1. According to Flutter's migration doc (https://dart.dev/null-safety/migration-guide#step5-publish) we need to bump the version to a major instead of minor, so that would be 2.0.0 instead of 1.1.0.

2. The 'example/ios/Flutter/flutter_export_environment.sh' file should not be commited, can you add it to the git ignore? You will also have to remove it from those 2 commits, the easiest way would be to simply do a `git reset de6b2abff8fcac0598da66b16535e3c05a990a6e` to un-commit your 2 commits (this will not delete any code your wrote), then update the gitignore and commit the changes. After that you should only have a single commit with all your changes but without the 'example/ios/Flutter/flutter_export_environment.sh' file in it.
Then you have to force push (since the git history was changed in the process) with `git push -f`

Let me know if you have any questions!

**Comment by lempiy** [comment]
> @lempiy That's almost ready for merging, there are 2 changes I'll request first though:
> 
> 1. According to Flutter's migration doc (https://dart.dev/null-safety/migration-guide#step5-publish) we need to bump the version to a major instead of minor, so that would be 2.0.0 instead of 1.1.0.
> 2. The 'example/ios/Flutter/flutter_export_environment.sh' file should not be commited, can you add it to the git ignore? You will also have to remove it from those 2 commits, the easiest way would be to simply do a `git reset de6b2abff8fcac0598da66b16535e3c05a990a6e` to un-commit your 2 commits (this will not delete any code your wrote), then update the gitignore and commit the changes. After that you should only have a single commit with all your changes but without the 'example/ios/Flutter/flutter_export_environment.sh' file in it.
>    Then you have to force push (since the git history was changed in the process) with `git push -f`
> 
> Let me know if you have any questions!

Bumped version
Rebased commits into one to squash `flutter_export_environment.sh`

**Review by quentinleguennec — APPROVED** [review]
Good to merge.

**Comment by quentinleguennec** [comment]
@lempiy  I puplished the new package, thanks for the PR!

**Comment by lempiy** [comment]
@quentinleguennec thanks.

**Pull request merged**
